# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - cd pvdf; go mod download
builds:
  - id: pvdf
    binary: pvdf
    dir: pvdf
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
release:
  prerelease: true
  extra_files:
    - glob: pvscanner/kubernetes/kustomized/deploy.yaml
    - glob: vgsd/vgsd
    - glob: vgsd/systemd/vgsd.service
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
